name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build and test frontend
        working-directory: frontend/r2d2-prototype-app
        run: |
          echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
          npm install
          npm run build
          npm run test
      
      - name: Build and test backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          python -m venv .venv
          source .venv/bin/activate
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          pip install -r requirements.txt
          pytest
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
      - name: Deploy frontend to S3
        working-directory: frontend/r2d2-prototype-app
        run: aws s3 sync build/ s3://r2d2-prototype-react-app
