name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build and test frontend
        working-directory: frontend/r2d2-prototype-app
        run: |
          echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
          npm install
          npm run build
          npm run test
      
    
      - name: Build and test backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          python -m venv .venv
          source .venv/bin/activate
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          pip install -r requirements.txt
          pytest
    
      - name: Deploy frontend
        run: |
          # Deploy the frontend using your chosen deployment method
          # Use ${{ secrets.FRONTEND_URL }} as the frontend URL in your deployment configuration
    
      - name: Deploy backend
        run: |
          # Deploy the backend using your chosen deployment method
          # Use ${{ secrets.BACKEND_URL }} as the backend URL in your deployment configuration
