name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build and test frontend
        working-directory: frontend/r2d2-prototype-app
        run: |
          echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
          npm install
          npm run build
          npm run test

      - name: Upload React build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: frontend/r2d2-prototype-app/build

      - name: Build and test backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          python -m venv .venv
          source .venv/bin/activate
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          pip install -r requirements.txt
          pytest tests

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Create Lambda deployment package
        run: |
          cd backend
          source .venv/bin/activate
          cd .venv/lib/python3.10/site-packages
          zip -r9 ../../../../lambda_function.zip .
          cd ../../../../
          zip -g lambda_function.zip app/main.py

      - name: Upload FastAPI zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda_function
          path: backend/lambda_function.zip


  CD:
      runs-on: ubuntu-latest
      needs: [CI]

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download React build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: frontend/r2d2-prototype-app/build

      - name: Download FastAPI zip file artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda_function
          path: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
      - name: Deploy frontend to S3
        working-directory: frontend
        run: aws s3 sync r2d2-prototype-app/build/ s3://r2d2-prototype-react-app

      - name: Deploy backend zip file to S3
        working-directory: backend
        run: aws s3 cp lambda_function.zip s3://r2d2-prototype-fastapi-backend
    
      - name: Deploy backend zip file to Lambda
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name r2d2-prototype-fastapi-lambda \
            --s3-bucket r2d2-prototype-fastapi-backend \
            --s3-key lambda_function.zip
          
          sleep 30

          aws lambda update-function-configuration \
            --function-name r2d2-prototype-fastapi-lambda \
            --environment "Variables={
              FRONTEND_URL=$FRONTEND_URL,
              OPENAI_API_KEY=$OPENAI_API_KEY
              }"
          