name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build and test frontend
        working-directory: frontend/r2d2-prototype-app
        run: |
          echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
          npm install
          npm run build
          npm run test
      
      - name: Build and test backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          python -m venv .venv
          source .venv/bin/activate
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          pip install -r requirements.txt
          pytest tests

      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/.venv') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Create Lambda deployment package
        run: |
          cd backend
          source .venv/bin/activate
          zip -r9 lambda_function.zip . -i .venv/lib/python3.9/site-packages/\*
          zip -g lambda_function.zip app/main.py
            
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
  
      # - name: Deploy frontend to S3
      #   working-directory: frontend/r2d2-prototype-app
      #   run: aws s3 sync build/ s3://r2d2-prototype-react-app

      # - name: Deploy backend zip file to S3
      #   run: aws s3 cp lambda_function.zip s3://r2d2-prototype-fastapi-backend
    

      # - name: Deploy backend to AWS Lambda
      #   working-directory: backend
      #   run: |
      #     # Add your deployment commands here
      #     # Example: aws lambda update-function-code --function-name your-function-name --zip-file fileb://lambda_function.zip
